version: '3.7'

services:
  caddy:
    image: caddy:2.3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  app:
    build: .
    command: rails server -b 0.0.0.0 -p 3000 -e production
    depends_on:
      - db
      - caddy
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
  db:
    image: postgres:12
    restart: unless-stopped
    env_file: .env

volumes:
  caddy_data:
  caddy_config: