version: '3.8'

services:
  web:
    build: .
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - database
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - database

networks:
  database:
    driver: bridge
