version: '3.8'

services:
  app:
    build: .
    container_name: negrosapp
    ports: 
      - "3001:3000"
    working_dir: /app
    volumes: 
      - .:/app
    depends_on:
      - db
    environment: 
      - RAILS_ADMIN_ROUTE=admin
  db:
    container_name: negrosdb
    image: postgres:11
    restart: on-failure
    environment: 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=negrosdev