"""empty message

Revision ID: adda91e02e52
Revises: 4086f13c168f
Create Date: 2021-11-21 15:28:00.754614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adda91e02e52'
down_revision = '4086f13c168f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'updated_on')
    # ### end Alembic commands ###
