default: &default
  adapter:  postgresql
  encoding: unicode
  pool:      <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:      <%= ENV["POSTGRES_HOST"] %>
  username:  <%= ENV["POSTGRES_USERNAME"] %>
  password:  <%= ENV["POSTGRES_PASSWORD"] %>
  port:      <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: negrosdev_dev

test:
  <<: *default
  database: negrosdev_test

production:
  url: <%= ENV["DATABASE_URL"] %>

