name: "Run rspec to execute tests"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: Set up application
        run: rake db:test:prepare
      - name: Run tests
        run: bundle exec rspec
